server:
  port: "${SERVER_PORT}"
  host: "${SERVER_HOST}"

database:
  host: "${DB_HOST}"
  port: "${DB_PORT}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  database: "${DB_NAME}"
  sslmode: "${DB_SSLMODE}"

redis:
  host: "${REDIS_HOST}"
  port: "${REDIS_PORT}"
  password: "${REDIS_PASSWORD}"

broker:
  oanda:
    api_key: "${OANDA_API_KEY}"
    account_id: "${OANDA_ACCOUNT_ID}"
    base_url: "${OANDA_BASE_URL}"

brave:
  api_key: "${BRAVE_API_KEY}"
  base_url: "${BRAVE_BASE_URL}"