-- soft delete columns
ALTER TABLE IF EXISTS trades ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS recommendations ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS market_data ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;


